import type { Metadata } from "next";
import "../globals.css";
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '700'], // Include both regular and bold weights
});

export const metadata: Metadata = {
  title: "Mitigation & Adaptation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}> 
        {children}
      </body>
    </html>
  );
}
